version: 2
multi-ecosystem-groups:
  all:
    schedule:
      interval: "monthly"
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all"
  - package-ecosystem: "bazel"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all"
  - package-ecosystem: "vcpkg"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all"
