# test.yml

name: test

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pre-commit/action@v3.0.1

  build-bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          bazel build //:wrap
          bazel test //tests/... --test_output=errors

  build-cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y autoconf autoconf-archive automake libtool pkg-config
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v11
      - run: |
          cmake --preset ninja-multi-vcpkg
          cmake --build --preset test
          ctest --preset test --output-on-failure
