# test.yml

name: test

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pre-commit/action@v3.0.1

  build-bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          bazel build //...
          bazel test //tests/... --test_output=errors
